# Copyright (c) 2025 Nordic Semiconductor ASA
# Copyright (c) 2025 Common Ground Electronics <https://cgnd.dev>
# SPDX-License-Identifier: Apache-2.0

# Originally adapted from https://github.com/nrfconnect/ncs-example-application/blob/main/.github/workflows/build-using-toolchain-bundle.yml

name: Build Firmware

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    outputs:
      nrf_toolchain_image_tag:
        # https://github.com/nrfconnect/sdk-nrf/pkgs/container/sdk-nrf-toolchain
        description: The sdk-nrf-toolchain image tag
        value: ${{ jobs.set_version_info.outputs.nrf_toolchain_image_tag }}
      build_version_tag:
        description: The build version tag
        value: ${{ jobs.set_version_info.outputs.build_version_tag }}
      build_version:
        description: The build version
        value: ${{ jobs.set_version_info.outputs.build_version }}

env:
  ARTIFACTS_PATH: ./artifacts
  PROJECT_RELATIVE_PATH: ${{ github.event.repository.name }}
  WEST_WORKSPACE_PATH: ./west-workspace

jobs:
  set_version_info:
    name: Set Version Info
    uses: ./.github/workflows/version-info.yml

  build_firmware:
    name: Build Firmware
    needs: set_version_info
    runs-on: ubuntu-latest
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ needs.set_version_info.outputs.nrf_toolchain_image_tag }}
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    strategy:
      matrix:
        board: ["thingy91x/nrf9151/ns"]
    steps:
      - name: Set sanitized board name
        run: |
          SANITIZED_BOARD_NAME=$(echo ${{ matrix.board }} | tr '/' '_')
          echo "SANITIZED_BOARD_NAME=$SANITIZED_BOARD_NAME"
          echo "SANITIZED_BOARD_NAME=$SANITIZED_BOARD_NAME" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: ${{ env.WEST_WORKSPACE_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}

      - name: Initialize west workspace
        working-directory: ${{ env.WEST_WORKSPACE_PATH }}
        run: |
          west init -l ${{ env.PROJECT_RELATIVE_PATH }}
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: ${{ env.WEST_WORKSPACE_PATH }}
        run: |
          west build -b ${{ matrix.board }} --pristine=always --sysbuild ${{ env.PROJECT_RELATIVE_PATH }}

      - name: Create build artifacts
        run: |
          mkdir -p ${{ env.ARTIFACTS_PATH }}
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/${{ env.PROJECT_RELATIVE_PATH }}/zephyr/.config ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}.config
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/dfu_application.zip ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}_dfu_application.zip
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/merged.hex ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}_merged.hex
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/${{ env.PROJECT_RELATIVE_PATH }}/zephyr/zephyr.elf ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}_zephyr.elf
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/${{ env.PROJECT_RELATIVE_PATH }}/zephyr/zephyr.hex ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}_zephyr.hex
          cp ${{ env.WEST_WORKSPACE_PATH }}/build/${{ env.PROJECT_RELATIVE_PATH }}/zephyr/zephyr.signed.bin ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT_RELATIVE_PATH }}_${{ needs.set_version_info.outputs.build_version_tag }}_${{ env.SANITIZED_BOARD_NAME }}_zephyr.signed.bin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts_${{ github.run_id }}_${{ env.SANITIZED_BOARD_NAME }}
          path: ${{ env.ARTIFACTS_PATH }}
          if-no-files-found: error
